# Site settings
baseURL = "https://alex-pracht.netlify.app/"
languageCode = "en-us"
title = "Portfolio website for Alex Pracht"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-180625706-1"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Alex Pracht"
  description = "MFA2021 student at London Business School "

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "/img/favicon_LBS.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Alex Pracht"
    subtitle = "Portfolio website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "LBS.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Elements"
      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    title = "Hi, my name is Alex"
    subtitle = "On this website I will display my work with R"
    buttonText = "I want to know more"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "xxxxxxxx"
      subtitle = "xxxx"
      image = "frankfurt.jpg"
      url = "post"

    [[params.tiles.showcase]]
      title = "Yield Curve Inversion"
      subtitle = "What US treasuries can predict"
      image = "pic02.jpg"
      url = "projects/project1/yieldcurve"

    [[params.tiles.showcase]]
      title = "Weather Anomalies"
      subtitle = "Does the data show statistically significant weather changes?"
      image = "pic02.jpg"
      url = "projects/project2/weatheranomalies"

    [[params.tiles.showcase]]
      title = "Aviation Case Study"
      subtitle = "Lufthansa Cargo Flight Schedule"
      image = "pic04.jpg"
      url = "/projects/project4/flightmap6"
      
    [[params.tiles.showcase]]
      title = "Download Alex's CV"
      subtitle = "CV Alexander Pracht 2020"
      image = ""
      url = "/projects/CV"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "My data analysis using R"
    subtitle = """During my studies at London Business School I developed my skills in data analysis and coding in R. 
    To see some analyses click on the link below."""
    buttonText = "Download Alex CV"
    href = "data/Alexander Pracht CV 2020.pdf"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send Alex a message"
    buttonClear = "Clear"
    formEmail = "apracht.mfa2021@london.edu"

    [[params.contact.email]]
    title = "Email"
    email = "apracht.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 (0)20 7000 7000"

    [[params.contact.address]]
    title = "Address"
    street = "London Business School"
    city = "London, Sussex Palace"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Alexander Pracht 2020"

    # Uses font awesome icons
    #[[params.footer.social]]
    #  icon = "fa-twitter"
    #  url= "https://www.twitter.com"
    #  label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/alex.pracht.3"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/alexprac"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/AlexanderPracht"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/alexander-pracht-871233151/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
