---
title: "FlightMap"
author: "Alexander Pracht"
date: "10/14/2020"
output: html_document
---
Using [this link](https://weiminwang.blog/2015/06/24/use-r-to-plot-flight-routes-on-a-fancy-world-background/):


```{r}
library(ggplot2)
library(maps)
library(rgeos)
library(maptools)
library(ggmap)
library(geosphere)
library(plyr)
library(rgdal)

urbanareasin <- readOGR("data/ne_10m_urban_areas/ne_10m_urban_areas.shp")
worldmap = map_data ("world")
wrld<-c(geom_polygon(aes(long,lat,group=group), size = 0.1, colour= "#090D2A", fill="#090D2A", alpha=0.8, data=worldmap))
 
urb <- c(geom_polygon(aes(long, lat, group = group),
size = 0.3,
color = "#ffffff",
fill = "#ffffff",
alpha = 1,
data = urbanareasin))
ggplot() + wrld + urb + theme(panel.background = element_rect(fill='#00001C',colour='#00001C'),
panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + annotate("text",x=max(worldmap$long),y=-60,hjust=.9,size=3,
label=paste("Created by Alexander Pracht",sep="\n"),color="white")

```

```{r}
library(ggplot2)
library(maps)
library(rgeos)
library(maptools)
library(ggmap)
library(geosphere)
library(plyr)
 
setwd('\your\directory')
rm(list = ls())
 
fortify.SpatialLinesDataFrame = function(model, data, ...){
ldply(model@lines, fortify)
}

lh_data = read.csv("data/LHcargo_FlightScheduleALL.csv", header=TRUE)

lh_data_sliced <-lh_data %>%
  select(DEP,ARR)

#df = read.csv('routes_all.csv', stringsAsFactor=F)
airports_dep = read.csv("data/airports.csv", header=FALSE)%>%
  select(V5, V7, V8)

colnames(airports_dep) <- c("DEP", "Lat_Dep", "Long_Dep")

airports_arr = read.csv("data/airports.csv", header=FALSE)%>%
  select(V5, V7, V8)

colnames(airports_arr) <- c("ARR", "Lat_Arr", "Long_Arr")

schedule_final <- left_join(lh_data_sliced, airports_arr)

schedule_final <- left_join(schedule_final, airports_dep)

library(data.table)
count.dups <- function(DF){
  DT <- data.table(DF)
  DT[,.N, by = names(DT)]
}

count_final <- count.dups(schedule_final)
count_final <- na.omit(count_final)

# calculate routes for each row
routes = gcIntermediate(count_final[,c('Long_Dep', 'Lat_Dep')], count_final[,c('Long_Arr', 'Lat_Arr')], addStartEnd=TRUE, breakAtDateLine=TRUE)

#, 200, breakAtDateLine = FALSE, addStartEnd = TRUE, sp=TRUE)
# fortify to dataframe
fortifiedroutes = fortify.SpatialLinesDataFrame(routes)
 
# merge to form great circles
routes_count = data.frame('count'=count_final$N, 'id'=1:nrow(count_final), 'Airport'=count_final$DEP)
#greatcircles = merge(fortifiedroutes, routes_count, all.x=T, by='id')
 
# get worldmap
worldmap = map_data ("world")

library(sf) 
urbanareasin <- readShapePoly("data/ne_10m_urban_areas/ne_10m_urban_areas.shp")
urb <- c(geom_polygon(aes(long, lat, group = group),
size = 0.3,
color = "#ffffff",
fill = "#ffffff",
alpha = 1,
data = urbanareasin))

# wrld layer
wrld<-c(geom_polygon(aes(long,lat,group=group), size = 0.1, colour= "#090D2A",
fill="#090D2A", alpha=0.8, data=worldmap))

# final combine
ggplot() +
wrld 
urb 

geom_segment(data= count_final, aes(y=Lat_Dep,x=Long_Dep, yend=Lat_Arr, xend=Long_Arr, colour=N), alpha = 0.3)+
theme(panel.background = element_rect(fill='#00001C',colour='#00001C'), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
theme(legend.position = c(0,0.4),
legend.justification = c(0,1),
legend.background = element_rect(colour = NA, fill = NA),
legend.key = element_rect(colour = NA, fill = NA, size = 10),
legend.text = element_text(colour='white', size = 20)) +
#guides(fill = guide_legend(keywidth = 20, keyheight = 20)) +
annotate("text",x=max(worldmap$long),y=-60,hjust=.9,size=6,
label=paste("Flights Cargo Lufthansa"),color="white")

```

